import type { NextConfig } from "next";

// One app, two halves:
//   /portal/*   the staff portal (Next.js routes in app/portal)
//   everything else: the static marketing site, generated by build/generate.js
//                    and copied into public/ by build/copy-public.mjs
//
// The redirects and headers below used to live in vercel.json; they moved
// here so `next start` behaves exactly like production.

const securityHeaders = [
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "X-Frame-Options", value: "SAMEORIGIN" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
  { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
];

const PAGES = ["services", "guides", "sectors", "projects", "about", "process", "contact", "faq", "testimonials", "privacy"];

const nextConfig: NextConfig = {
  poweredByHeader: false,
  // Node packages that must not be bundled.
  serverExternalPackages: ["@react-pdf/renderer", "exceljs"],

  async rewrites() {
    return {
      // public/ holds index.html, but Next only serves it at /index.html.
      beforeFiles: [{ source: "/", destination: "/index.html" }],
      afterFiles: [],
      fallback: [],
    };
  },

  async redirects() {
    return [
      { source: "/index.html", destination: "/", permanent: true },

      // staff shortcuts
      { source: "/login", destination: "/portal/login", permanent: false },
      { source: "/timesheet", destination: "/portal/login", permanent: false },
      { source: "/staff", destination: "/portal/login", permanent: false },

      // extensionless marketing URLs -> the real .html pages
      ...PAGES.map((p) => ({ source: `/${p}`, destination: `/${p}.html`, permanent: true })),
      { source: "/services/:slug([^.]+)", destination: "/services/:slug.html", permanent: true },
      { source: "/guides/:slug([^.]+)", destination: "/guides/:slug.html", permanent: true },
    ];
  },

  async headers() {
    return [
      { source: "/(.*)", headers: securityHeaders },
      {
        // the portal must never be indexed or framed
        source: "/portal/:path*",
        headers: [
          { key: "X-Robots-Tag", value: "noindex, nofollow" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "Cache-Control", value: "private, no-store" },
        ],
      },
      {
        // fingerprinted with ?v= by the generator, so safe to cache forever
        source: "/(assets/.*|styles.css|main.js|favicon.ico)",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
    ];
  },
};

export default nextConfig;
